# Provide a custom message
message: ""

# Remember to set service.type=ClusterIP if you are using an ingress
ingress:
  configured: false
  rewritePath: true
  pathPrefix: ""

service:
  type: ClusterIP
  port: 8080

deployment:
  replicaCount: 2
  container:
    image:
      repository: "harbor.18.143.86.236.sslip.io/demo/hello-k8s"
      tag: "1.11.1" # uses chart appVersion if not provided
      pullPolicy: Always # IfNotPresent
    port: 8080

  # Currently only linux images on amd64 architecture are supported - support for arm64 and windows/amd64 coming ...
  nodeSelector:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64

  resources: {}

  tolerations: []

  affinity: {}

